import '../css/invitation.css';
import { createIcons, ArrowUpRight, ArrowRight, House, Heart, CalendarDays, Images, Gift, MessageCircleHeart, MailOpen, MoveDown, Gem, Wine, MapPin, CalendarPlus, Video, Play, Expand, CreditCard, Package, Nfc, Copy, Send, Sparkles, HeartPulse, HandHeart, Music2, X, ChevronLeft, ChevronRight } from 'lucide';
const w = window.__WEDDING__;

const icons = { ArrowUpRight, ArrowRight, House, Heart, CalendarDays, Images, Gift, MessageCircleHeart, MailOpen, MoveDown, Gem, Wine, MapPin, CalendarPlus, Video, Play, Expand, CreditCard, Package, Nfc, Copy, Send, Sparkles, HeartPulse, HandHeart, Music2, X, ChevronLeft, ChevronRight };
const icon = (name, cls = '') => `<i data-lucide="${name}" class="${cls}" aria-hidden="true"></i>`;
const esc = (value) => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names = `${w.bride.name} & ${w.groom.name}`;
const initials = [w.bride.name[0], w.groom.name[0]];
const weddingDate = new Date(w.date);
const datePart = options => new Intl.DateTimeFormat('id-ID', { timeZone: 'Asia/Jakarta', ...options }).format(weddingDate);
const day = datePart({ day: '2-digit' });
const month = datePart({ month: '2-digit' });
const monthName = datePart({ month: 'long' }).toUpperCase();
const year = datePart({ year: 'numeric' });
const weekday = datePart({ weekday: 'long' });
const formattedDate = `${day} . ${month} . ${year}`;
document.title = `${names} — A Love Written in the Stars`;
const flourish = '<div class="flourish" aria-hidden="true"><span></span>✧<span></span></div>';
const flower = (cls = '', file = 'chrysanthemum') => `<div class="lottie ${cls}" data-animation="${file}" aria-hidden="true"></div>`;
const heading = (eyebrow, title, text = '') => `<div class="section-heading reveal"><span class="eyebrow">${eyebrow}</span><h2>${title}</h2>${flourish}${text ? `<p>${text}</p>` : ''}</div>`;
const nav = [['home','Beranda','house'],['mempelai','Mempelai','heart'],['acara','Acara','calendar-days'],['galeri','Galeri','images'],['hadiah','Hadiah','gift'],['ucapan','Ucapan','message-circle-heart']];
const photos = [
  {src:'/images/wedding.jpg', title:'The beginning of forever', desc:'Momen kebersamaan dalam suasana pernikahan'},
  {src:'/images/moment.jpg', title:'Every little moment', desc:'Potret pasangan di hari pernikahan'},
  {src:'/images/ceremony.jpg', title:'A day to remember', desc:'Suasana upacara pernikahan'},
];
const guest = w.guestName || new URLSearchParams(location.search).get('to')?.trim().slice(0, 100) || 'Bapak / Ibu / Saudara/i';

document.querySelector('#app').innerHTML = `
  <div class="reading-progress" aria-hidden="true"></div>
  <header class="site-header"><a class="monogram" href="#home" aria-label="${names} — beranda">${initials[0]}<span>&</span>${initials[1]}</a><nav aria-label="Navigasi utama">${nav.map(([id,label])=>`<a href="#${id}">${label}</a>`).join('')}</nav><a class="header-date" href="#acara">${day} <span>·</span> ${month} <span>·</span> ${year} ${icon('arrow-up-right')}</a></header>
  <main>
    <section class="hero" id="home">
      <div class="hero-grain" aria-hidden="true"></div><div class="particles" aria-hidden="true">${Array.from({length:22},(_,i)=>`<span style="--x:${(i*47)%100}%;--delay:-${i*.7}s;--duration:${12+i%7}s;--size:${2+i%3}px"></span>`).join('')}</div>
      <div class="hero-side-label">TOGETHER IS A BEAUTIFUL PLACE TO BE</div>
      <div class="hero-copy"><div class="hero-kicker"><span></span> THE WEDDING OF</div><h1>${w.bride.name}<em>&</em>${w.groom.name}</h1><p class="hero-tagline">A love written in the stars.</p><div class="hero-date"><span>${weekday}</span><b>${formattedDate}</b><span>${w.city}</span></div><div class="guest"><span>Kepada yang terkasih,</span><p>${esc(guest)}</p></div><button class="button gold" id="open-invitation">${icon('mail-open')} Buka Undangan ${icon('arrow-right')}</button><span class="hero-footnote">Dengan cinta, kami mengundang Anda.</span></div>
      <div class="hero-art"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><span class="art-star star-one">✧</span><span class="art-star star-two">✦</span><div class="photo-arch"><img src="/images/wedding.jpg" alt="Foto contoh pasangan pada hari pernikahan" fetchpriority="high"/><div class="photo-shade"></div><span class="photo-caption">and so, our forever begins</span></div><div class="photo-seal"><span>WITH LOVE</span><b>${initials[0]} & ${initials[1]}</b><span>EST. ${year}</span></div>${flower('hero-flower flower-left')}${flower('hero-flower flower-right')}${flower('hero-leaf','flower')}<div class="art-caption"><span>ONE LOVE.</span><span>A LIFETIME OF US.</span></div></div>
      <a href="#pembuka" class="scroll-cue"><span>SCROLL TO DISCOVER</span>${icon('move-down')}</a><span class="hero-edition">THE WEDDING EDITION — 01</span>
    </section>
    <section class="blessing section" id="pembuka">${flower('blessing-flower','flower')}<div class="reveal"><span class="eyebrow">BISMILLAHIRRAHMANIRRAHIM</span><p class="arabic" lang="ar" dir="rtl">وَخَلَقْنَاكُمْ أَزْوَاجًا</p><h2>Dua hati, satu perjalanan.</h2><p class="verse">“Dan Kami menciptakan kamu berpasang-pasangan.”</p><span class="verse-source">QS. AN-NABA’ : 8</span>${flourish}<h3>Assalamu’alaikum Warahmatullahi Wabarakatuh</h3><p class="intro-text">Dengan memohon rahmat dan rida Allah SWT, kami bermaksud mengundang Bapak/Ibu/Saudara/i untuk menjadi bagian dari hari bahagia pernikahan kami.</p></div></section>
    <section class="couple section" id="mempelai">${heading('THE BRIDE & THE GROOM','Ketika aku menemukan <em>kamu.</em>','Dua cerita yang berbeda, dipertemukan untuk menulis kisah yang sama.')}<div class="couple-grid"><article class="person reveal"><div class="person-portrait bride-portrait"><img src="/images/moment.jpg" alt="Foto ilustrasi mempelai wanita" loading="lazy"/><span>THE BRIDE</span></div><span class="script-name">${w.bride.name}</span><h3>${w.bride.fullName}</h3><p>${w.bride.order}<br><strong>${w.bride.parents}</strong></p></article><span class="couple-and reveal">&</span><article class="person reveal"><div class="person-portrait groom-portrait"><img src="/images/wedding.jpg" alt="Foto ilustrasi mempelai pria" loading="lazy"/><span>THE GROOM</span></div><span class="script-name">${w.groom.name}</span><h3>${w.groom.fullName}</h3><p>${w.groom.order}<br><strong>${w.groom.parents}</strong></p></article></div></section>
    <section class="countdown-section section">${heading('EVERY SECOND BRINGS US CLOSER','Menuju hari <em>bahagia.</em>')}<div class="countdown reveal" aria-label="Hitung mundur pernikahan">${['Hari','Jam','Menit','Detik'].map((label,i)=>`<div><b id="count-${i}">00</b><span>${label}</span></div>`).join('')}</div><p class="countdown-caption">Tak sabar berbagi momen ini bersama Anda.</p></section>
    <section class="events section" id="acara">${heading('SAVE THE DATE','Janji suci & <em>perayaan.</em>','Dengan penuh kebahagiaan, kami menantikan kehadiran dan doa restu Anda.')}<div class="event-grid">${w.events.map((e,i)=>`<article class="event-card reveal"><div class="event-number">0${i+1}</div><div class="event-icon">${icon(e.icon)}</div><span class="eyebrow">${i===0?'THE SACRED PROMISE':'THE CELEBRATION'}</span><h3>${e.name}</h3><div class="event-date"><b>${day}</b><span>${monthName}<br>${year}</span></div><p>${weekday} · ${e.time}</p><div class="fine-rule"></div><h4>${w.venue}</h4><p class="address">${w.address}</p><a class="button outline" href="${w.mapUrl}" target="_blank" rel="noopener noreferrer">${icon('map-pin')} Petunjuk Lokasi ${icon('arrow-up-right')}</a><button class="calendar-link" data-calendar="${i}">${icon('calendar-plus')} Simpan ke Kalender</button></article>`).join('')}</div><div class="streaming reveal"><div class="streaming-icon">${icon('video')}</div><div><span class="eyebrow">CELEBRATE FROM ANYWHERE</span><h3>Jarak tak membatasi doa.</h3><p>Ikuti prosesi akad kami melalui siaran langsung.</p></div><button class="button outline" id="stream-button">${icon('play')} Live Streaming</button></div></section>
    <section class="story section">${heading('OUR LITTLE STORY','Semesta punya <em>rencana.</em>')}<div class="story-grid">${[['2022','Pertemuan pertama','Sebuah pertemuan sederhana, percakapan yang terasa berbeda. Siapa sangka, dari sanalah semuanya bermula.'],['2024','Memilih bersama','Dari banyak cerita dan perjalanan, kami belajar bahwa rumah bukan selalu tempat. Terkadang, ia adalah seseorang.'],['2026','Selamanya, dimulai','Dengan restu kedua keluarga, kami memilih melangkah bersama. Satu janji, satu tujuan, untuk seumur hidup.']].map(([year,title,text])=>`<article class="story-item reveal"><span class="story-year">${year}</span><span class="story-dot"></span><h3>${title}</h3><p>${text}</p></article>`).join('')}</div></section>
    <section class="gallery section" id="galeri">${heading('A COLLECTION OF US','Sepotong waktu, <em>selamanya.</em>','Momen kecil yang menjadi bagian paling indah dari cerita kami.')}<div class="gallery-grid">${photos.map((p,i)=>`<button class="gallery-image reveal" data-photo="${i}" aria-label="Perbesar foto: ${p.desc}"><img src="${p.src}" alt="${p.desc}" loading="lazy"/><span class="gallery-overlay"><span>${p.title}</span>${icon('expand')}</span><span class="gallery-index">0${i+1}</span></button>`).join('')}</div><p class="gallery-note">A little glimpse of our forever.</p></section>
    <section class="gifts section" id="hadiah">${flower('gift-flower','flower')}${heading('A GIFT FROM THE HEART','Tanda <em>kasih.</em>','Kehadiran dan doa restu Anda adalah hadiah terindah bagi kami. Jika ingin berbagi tanda kasih, kami menerimanya dengan penuh rasa syukur.')}<div class="gift-tabs reveal" role="tablist" aria-label="Pilihan hadiah"><button class="active" id="transfer-tab" role="tab" aria-selected="true" aria-controls="transfer-panel">${icon('credit-card')} Transfer Bank</button><button id="package-tab" role="tab" aria-selected="false" aria-controls="package-panel" tabindex="-1">${icon('package')} Kirim Kado</button></div><div id="transfer-panel" role="tabpanel" aria-labelledby="transfer-tab"><div class="bank-grid">${w.accounts.map((a,i)=>`<article class="bank-card reveal"><div class="bank-top"><span class="bank-brand">${a.bank}</span>${icon('nfc')}</div><span class="bank-label">NOMOR REKENING</span><p class="account-number">${a.number}</p><div class="bank-bottom"><div><span class="bank-label">ATAS NAMA</span><p>${a.holder}</p></div><button class="copy-button" data-copy="${i}" aria-label="Salin rekening ${a.bank}">${icon('copy')} <span>Salin</span></button></div></article>`).join('')}</div>${w.demo?'<p class="demo-note">Rekening contoh · Jangan melakukan transfer ke nomor ini.</p>':''}</div><div id="package-panel" role="tabpanel" aria-labelledby="package-tab" hidden><div class="package-card">${icon('gift')}<h3>Kirim sebuah kebahagiaan</h3><p>${w.giftAddress}</p><button class="button outline" id="copy-address">${icon('copy')} Salin Alamat</button>${w.demo?'<small>Alamat contoh untuk pratinjau undangan.</small>':''}</div></div></section>
    <section class="wishes section" id="ucapan">${heading('YOUR PRESENCE MEANS EVERYTHING','Doa, cinta & <em>kehadiran.</em>','Tinggalkan sepatah doa dan kabarkan kehadiran Anda di hari istimewa kami.')}<div class="wishes-grid"><form id="rsvp-form" class="rsvp-form reveal"><h3>Untuk hari bahagia kami</h3><div class="hp-field" aria-hidden="true"><label for="website">Website</label><input id="website" name="website" tabindex="-1" autocomplete="off"/></div><label for="guest-name">Nama lengkap <span>*</span></label><input id="guest-name" name="name" placeholder="Nama Anda" required maxlength="70" autocomplete="name" value="${esc(w.guestName || '')}" ${w.guestName?'readonly':''}/><div class="form-row"><div><label for="attendance">Konfirmasi kehadiran <span>*</span></label><select id="attendance" name="attendance" required><option value="">Pilih kehadiran</option><option value="yes">Dengan senang hati hadir</option><option value="no">Maaf, belum bisa hadir</option></select></div><div><label for="guests">Jumlah tamu</label><select id="guests" name="guests"><option value="1">1 orang</option><option value="2">2 orang</option><option value="3">3 orang</option><option value="4">4 orang</option></select></div></div><label for="wish-message">Doa & ucapan <span>*</span></label><textarea id="wish-message" name="message" placeholder="Tuliskan doa dan harapan terbaik Anda…" rows="4" required maxlength="600"></textarea><button class="button gold" type="submit">Kirim Ucapan ${icon('send')}</button><p class="form-note">Ucapan akan diperiksa sebelum ditampilkan sesuai pengaturan mempelai.</p><p id="form-status" role="status"></p></form><div class="wish-wall reveal"><div class="wish-wall-header"><h3>Peluk hangat dari kalian</h3><span id="wish-count"></span></div><div id="wish-list"></div></div></div></section>
    <section class="etiquette section"><div class="reveal"><span class="eyebrow">A LITTLE NOTE FOR OUR GUESTS</span><h2>Merayakan dengan nyaman.</h2><p>Dengan penuh perhatian, mari menjaga kenyamanan bersama.</p><div class="etiquette-grid"><div>${icon('sparkles')}<span>Jaga kebersihan<br>tangan</span></div><div>${icon('heart-pulse')}<span>Hadir dalam<br>kondisi sehat</span></div><div>${icon('hand-heart')}<span>Saling menjaga<br>dan menghargai</span></div></div></div></section>
    <footer class="closing section">${flower('closing-flower','footer')}<div class="reveal"><span class="eyebrow">THE BEGINNING OF OUR FOREVER</span><h2>Terima kasih.</h2><p>Merupakan suatu kehormatan dan kebahagiaan bagi kami<br>apabila Anda berkenan hadir dan memberikan doa restu.</p><span class="closing-names">${names}</span><p class="closing-greeting">Wassalamu’alaikum Warahmatullahi Wabarakatuh</p>${flourish}<span class="eyebrow">KAMI YANG BERBAHAGIA</span><div class="families">${w.families.map(f=>`<p>${f}</p>`).join('')}</div><p class="inviting">Turut mengundang: segenap keluarga besar kedua mempelai.</p><div class="vendors"><span>WITH OUR LOVELY VENDORS</span><div>${w.vendors.map(v=>`<span>${v}</span>`).join('')}</div></div><a class="footer-brand" href="#home">senandika<span>CRAFTED WITH LOVE</span></a></div></footer>
  </main>
  <nav class="mobile-nav" aria-label="Navigasi seluler">${nav.map(([id,label,ico])=>`<a href="#${id}" aria-label="${label}">${icon(ico)}<span>${label}</span></a>`).join('')}</nav>
  <div class="floating-controls"><button id="motion-toggle" aria-label="Jeda animasi" title="Jeda animasi" aria-pressed="false">${icon('sparkles')}</button><button id="music-toggle" aria-label="Putar musik" title="Putar musik" aria-pressed="false">${icon('music-2')}<span class="music-bars"><i></i><i></i><i></i></span></button></div>
  <div class="toast" role="status" aria-live="polite"></div>
  <dialog id="lightbox" aria-label="Galeri foto"><button class="dialog-close" aria-label="Tutup galeri">${icon('x')}</button><button class="lightbox-prev" aria-label="Foto sebelumnya">${icon('chevron-left')}</button><figure><img src="" alt=""/><figcaption></figcaption></figure><button class="lightbox-next" aria-label="Foto berikutnya">${icon('chevron-right')}</button></dialog>
  <dialog id="stream-dialog" class="info-dialog" aria-labelledby="stream-title"><button class="dialog-close" aria-label="Tutup informasi streaming">${icon('x')}</button>${icon('video')}<span class="eyebrow">LIVE STREAMING</span><h2 id="stream-title">Sampai jumpa di hari bahagia.</h2><p>Tautan siaran langsung akan tersedia menjelang acara.</p><p>${w.dateLabel}<br>Mulai pukul ${w.events[0].time.split(' – ')[0]} WIB</p><button class="button gold" data-calendar="0">${icon('calendar-plus')} Ingatkan Saya</button></dialog>
`;
createIcons({icons, attrs:{'stroke-width':1.5}});

let toastTimer;
function toast(message) { const el=document.querySelector('.toast'); el.textContent=message; el.classList.add('visible'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>el.classList.remove('visible'),3500); }

// Reveal elements as they enter the viewport; content stays visible without JS/CSS animation support.
const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');revealObserver.unobserve(e.target);}}),{threshold:.08});
document.querySelectorAll('.reveal').forEach((el)=>{el.classList.add('will-reveal');revealObserver.observe(el);});
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
let motionPaused=reducedMotion.matches;
let animationInstances=[];
document.documentElement.classList.toggle('motion-paused',motionPaused);
import('lottie-web/build/player/lottie_light').then(({default:lottie}) => {
const animationObserver=new IntersectionObserver(entries=>entries.forEach(({target,isIntersecting})=>{const a=animationInstances.find(a=>a.container===target);if(a){a.visible=isIntersecting;if(isIntersecting&&!motionPaused&&!document.hidden)a.instance.play();else a.instance.pause();}}),{rootMargin:'80px'});
const lazyAnimationObserver=new IntersectionObserver(entries=>entries.forEach(({target,isIntersecting})=>{if(!isIntersecting)return;lazyAnimationObserver.unobserve(target);const instance=lottie.loadAnimation({container:target,renderer:'svg',loop:true,autoplay:!motionPaused,path:`/lottie/${target.dataset.animation}.json`,rendererSettings:{preserveAspectRatio:'xMidYMid meet'}});instance.setSpeed(.65);instance.addEventListener('DOMLoaded',()=>{if(motionPaused)instance.goToAndStop(90,true);});animationInstances.push({container:target,instance,visible:true});animationObserver.observe(target);}),{rootMargin:'160px'});
document.querySelectorAll('[data-animation]').forEach(el=>lazyAnimationObserver.observe(el));
}).catch(() => { document.querySelectorAll('[data-animation]').forEach(el => { el.innerHTML='<img src="/images/flower.png" alt="" />'; }); });
function updateMotion(){document.documentElement.classList.toggle('motion-paused',motionPaused);const b=document.querySelector('#motion-toggle');b.setAttribute('aria-pressed',String(motionPaused));b.setAttribute('aria-label',motionPaused?'Putar animasi':'Jeda animasi');b.title=motionPaused?'Putar animasi':'Jeda animasi';animationInstances.forEach(a=>motionPaused||!a.visible||document.hidden?a.instance.pause():a.instance.play());}
document.querySelector('#motion-toggle').addEventListener('click',()=>{motionPaused=!motionPaused;updateMotion();toast(motionPaused?'Animasi dijeda':'Animasi diputar');});
reducedMotion.addEventListener('change',e=>{motionPaused=e.matches;updateMotion();});
document.addEventListener('visibilitychange',updateMotion);
updateMotion();

function updateCountdown(){const seconds=Math.max(0,Math.floor((new Date(w.date)-Date.now())/1000));[Math.floor(seconds/86400),Math.floor(seconds/3600)%24,Math.floor(seconds/60)%60,seconds%60].forEach((v,i)=>document.querySelector(`#count-${i}`).textContent=String(v).padStart(2,'0'));if(seconds===0)document.querySelector('.countdown-caption').textContent='Hari bahagia kami telah tiba. Terima kasih atas doa Anda.';}
updateCountdown();setInterval(updateCountdown,1000);
let scrollPending=false;
window.addEventListener('scroll',()=>{if(scrollPending)return;scrollPending=true;requestAnimationFrame(()=>{const max=document.documentElement.scrollHeight-innerHeight;document.querySelector('.reading-progress').style.transform=`scaleX(${max>0?scrollY/max:0})`;document.querySelector('.site-header').classList.toggle('scrolled',scrollY>40);scrollPending=false;});},{passive:true});
const navObserver=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting)document.querySelectorAll('.site-header nav a,.mobile-nav a').forEach(a=>{const active=a.hash===`#${e.target.id}`;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});},{rootMargin:'-20% 0px -65% 0px'});
nav.forEach(([id])=>navObserver.observe(document.getElementById(id)));

// A quiet original ambient melody, generated locally. Starts only after a user gesture.
let audioContext, musicTimer, musicPlaying=false, noteIndex=0;
const melody=[261.63,329.63,392,523.25,440,392,329.63,293.66,220,261.63,329.63,440,392,329.63,293.66,261.63];
function playNote(){if(!musicPlaying)return;const t=audioContext.currentTime;const note=melody[noteIndex++%melody.length];[1,2].forEach((multiple,i)=>{const osc=audioContext.createOscillator();const gain=audioContext.createGain();osc.type='sine';osc.frequency.value=note*multiple;gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(i?.014:.045,t+.04);gain.gain.exponentialRampToValueAtTime(.0001,t+2.4);osc.connect(gain);gain.connect(audioContext.destination);osc.start(t);osc.stop(t+2.5);});}
async function toggleMusic(){try{if(!audioContext)audioContext=new (window.AudioContext||window.webkitAudioContext)();if(musicPlaying){musicPlaying=false;clearInterval(musicTimer);await audioContext.suspend();}else{await audioContext.resume();musicPlaying=true;playNote();musicTimer=setInterval(playNote,750);}const b=document.querySelector('#music-toggle');b.classList.toggle('playing',musicPlaying);b.setAttribute('aria-pressed',String(musicPlaying));b.setAttribute('aria-label',musicPlaying?'Jeda musik':'Putar musik');b.title=musicPlaying?'Jeda musik':'Putar musik';}catch{toast('Musik belum didukung pada browser ini.');}}
document.querySelector('#music-toggle').addEventListener('click',toggleMusic);
document.querySelector('#open-invitation').addEventListener('click',()=>{document.body.classList.add('invitation-open');document.querySelector('#pembuka').scrollIntoView({behavior:motionPaused?'instant':'smooth'});if(!musicPlaying)toggleMusic();});

document.querySelectorAll('[data-calendar]').forEach(button=>button.addEventListener('click',()=>{const e=w.events[Number(button.dataset.calendar)];const calendarEscape=s=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');const ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Senandika//Wedding//ID','CALSCALE:GREGORIAN','BEGIN:VEVENT',`UID:levi-dio-${button.dataset.calendar}-20261212@senandika.local`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}`,`DTSTART:${e.start}`,`DTEND:${e.end}`,`SUMMARY:${calendarEscape(`${e.name} — ${names}`)}`,`LOCATION:${calendarEscape(`${w.venue}, ${w.address}`)}`,'DESCRIPTION:Terima kasih telah menjadi bagian dari hari bahagia kami.','END:VEVENT','END:VCALENDAR'].join('\r\n');const url=URL.createObjectURL(new Blob([ics],{type:'text/calendar;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`${e.name.toLowerCase().replace(/ /g,'-')}-levi-dio.ics`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Undangan kalender berhasil diunduh.');}));
document.querySelector('#stream-button').addEventListener('click',()=>{if(w.streamingUrl)window.open(w.streamingUrl,'_blank','noopener,noreferrer');else document.querySelector('#stream-dialog').showModal();});

async function copyText(text){try{await navigator.clipboard.writeText(text);toast('Berhasil disalin ke clipboard.');return true;}catch{toast('Tidak dapat menyalin otomatis. Silakan salin teks yang ditampilkan.');return false;}}
document.querySelectorAll('[data-copy]').forEach(b=>b.addEventListener('click',async()=>{if(await copyText(w.accounts[Number(b.dataset.copy)].number)){b.querySelector('span').textContent='Tersalin';setTimeout(()=>b.querySelector('span').textContent='Salin',2500);}}));
document.querySelector('#copy-address').addEventListener('click',()=>copyText(w.giftAddress));
const tabs=[document.querySelector('#transfer-tab'),document.querySelector('#package-tab')];
function setTab(index){tabs.forEach((tab,i)=>{tab.classList.toggle('active',index===i);tab.setAttribute('aria-selected',String(index===i));tab.tabIndex=index===i?0:-1;document.getElementById(tab.getAttribute('aria-controls')).hidden=index!==i;});}
tabs.forEach((tab,index)=>{tab.addEventListener('click',()=>setTab(index));tab.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?1:1-index;setTab(next);tabs[next].focus();}});});

const initialWishes=Array.isArray(w.wishes)?w.wishes:[];
let saved=[];
function renderWishes(){const list=[...saved,...initialWishes];document.querySelector('#wish-count').textContent=`${list.length} ucapan`;document.querySelector('#wish-list').innerHTML=list.map(x=>`<article class="wish"><div class="wish-avatar">${esc(x.name[0]?.toUpperCase()||'♡')}</div><div><div class="wish-name"><h4>${esc(x.name)}</h4><span class="attendance-badge ${x.attendance==='yes'?'attending':''}">${x.attendance==='yes'?'Hadir':'Berhalangan'}</span></div><p>${esc(x.message)}</p><span class="wish-time">${x.sample?'Ucapan contoh':'Ditampilkan oleh mempelai'}</span></div></article>`).join('');}
renderWishes();
document.querySelector('#attendance').addEventListener('change',e=>{const guests=document.querySelector('#guests');guests.disabled=e.target.value==='no';});
document.querySelector('#rsvp-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;const data=new FormData(form);const entry={name:data.get('name').trim(),attendance:data.get('attendance'),guests:data.get('attendance')==='no'?0:Number(data.get('guests')),message:data.get('message').trim(),guest_token:w.guestToken||null,website:data.get('website')};if(!entry.name||!entry.message){toast('Nama dan ucapan tidak boleh hanya berisi spasi.');return;}const submit=form.querySelector('[type=submit]');submit.disabled=true;const status=document.querySelector('#form-status');try{const response=await fetch(w.rsvpEndpoint,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':w.csrfToken},body:JSON.stringify(entry)});const result=await response.json();if(!response.ok)throw new Error(result.message||'Ucapan belum terkirim.');if(result.status==='approved'&&result.wish){saved=[result.wish,...saved];renderWishes();}form.reset();if(w.guestName)document.querySelector('#guest-name').value=w.guestName;document.querySelector('#guests').disabled=false;status.textContent=result.message;toast(result.message);}catch(error){status.textContent=error.message||'Ucapan belum terkirim. Silakan coba lagi.';}finally{submit.disabled=false;}});

const lightbox=document.querySelector('#lightbox');let photoIndex=0;
function showPhoto(index){photoIndex=(index+photos.length)%photos.length;const p=photos[photoIndex];lightbox.querySelector('img').src=p.src;lightbox.querySelector('img').alt=p.desc;lightbox.querySelector('figcaption').textContent=`${p.title} — ${photoIndex+1} / ${photos.length}`;}
document.querySelectorAll('[data-photo]').forEach(b=>b.addEventListener('click',()=>{showPhoto(Number(b.dataset.photo));lightbox.showModal();}));
lightbox.querySelector('.lightbox-prev').addEventListener('click',()=>showPhoto(photoIndex-1));lightbox.querySelector('.lightbox-next').addEventListener('click',()=>showPhoto(photoIndex+1));
lightbox.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')showPhoto(photoIndex-1);if(e.key==='ArrowRight')showPhoto(photoIndex+1);});
document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.dialog-close').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});});

